var Chance = require('chance');
const mainPage = require('../githubpages/main.page')
const joinPage = require('../githubpages/join.page')
const loginPage = require('../githubpages/login.page')
const logginedPage = require('../githubpages/loginned.page')
const passwordResetPage = require('../githubpages/password_reset.page')
const pricingPage = require('../githubpages/pricing.page')
const explorePage = require('../githubpages/explore.page')
const topicsPage = require ('../githubpages/topics.page')
const searchWebdriverioPage = require ('../githubpages/search_webdriverio.page')
const enterprisePage = require ('../githubpages/enterprise.page')
const enterprisePlanPage = require ('../githubpages/enterprise_plan.page')
const enterpriseTrialSignUpPage = require ('../githubpages/enterprise_trial_signup.page');
const careersPage = require ('../githubpages/careers.page')

describe('github testing', () => {

    it('label "verify your account" is displayed in viewport', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        var chance = new Chance()
        const email = chance.email()
        mainPage.setEmail(email)
        browser.pause(1000)
        mainPage.clickSignUpForGithubButton()
        isRightUrl = joinPage.currentUrl() === 'https://github.com/join'
        console.log('We are on login page : ' + isRightUrl)
        const verifyLabel = joinPage.verifyLabel()
        console.log('"Verify your account" is displayed : ' + verifyLabel.isDisplayedInViewport())
    })    

    it('set random values', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        browser.pause(1000)
        mainPage.clickSignUpForGithubButton()
        var chance = new Chance()
        const userName = chance.string({ pool : 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' , length : chance.integer({ min : 5, max : 10 }) })
        const userEmail = chance.email()
        const pass = chance.string({length : 8})
        isRightUrl = joinPage.currentUrl() === 'https://github.com/join'
        console.log('We are on sign up page : ' + isRightUrl)
        joinPage.setUserName(userName)
        browser.pause(500)
        joinPage.setUserEmail(userEmail)
        browser.pause(500)
        joinPage.setPass(pass)
        browser.pause(2000)

    })

    it('sign in with valid log and pass', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        browser.pause(1000)
        mainPage.clickSignInButton()
        const userName = 'testName6622'
        const pass = 'testname86478846'
        loginPage.setUserNameEmail(userName)
        browser.pause(500)
        loginPage.setPass(pass)
        browser.pause(500)
        loginPage.clickSignInButton()
        browser.pause(1000)
        logginedPage.clickAvatarImageButton()
        const nickname = logginedPage.nickName()
        isChecked = nickname.getText() === 'testName6622'
        console.log('We are loggined : ' + isChecked)
        logginedPage.clickSignOutButton()
        browser.pause(1000)
    })

    it('forgot password function testing', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        browser.pause(1000)
        mainPage.clickSignInButton()
        browser.pause(1000)
        loginPage.clickForgotPassButton()
        browser.pause(1000)
        var chance = new Chance()
        const userEmail = chance.email()
        passwordResetPage.setUserEmail(userEmail)
        browser.pause(2000)
    })

    it('moveTo function check', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        browser.pause(1000)
        mainPage.moveToWhyGithubButton()
        browser.pause(1000)
        mainPage.moveToExploreButton()
        browser.pause(1000)
        mainPage.moveToPricingButton()
        browser.pause(1000)
        isExistingGithub = mainPage.whyGithubButton.isExisting()
        console.log('GitHub button exists : ' + isExistingGithub)
        isExistingExplore = mainPage.exploreButton.isExisting()
        console.log('Explore button exists : ' + isExistingExplore)
        isExistingPricing = mainPage.pricingButton.isExisting()
        console.log('Pricing button exists : ' + isExistingPricing)
        mainPage.clickPlansButton()
        browser.pause(1000)
        pricingPage.clickJoinForFreeButton()
        browser.pause(1000)
        var chance = new Chance()
        const userName = chance.string({ pool : 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' , length : chance.integer({ min : 5, max : 10 }) })
        const userEmail = chance.email()
        const pass = chance.string({length : 8})
        joinPage.setUserName(userName)
        browser.pause(500)
        joinPage.setUserEmail(userEmail)
        browser.pause(500)
        joinPage.setPass(pass)
        browser.pause(2000)
    })

    it('test visible function', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        mainPage.moveToExploreButton()
        browser.pause(1000)
        mainPage.clickExploreGithubButton()
        browser.pause(1000)
        explorePage.clickTopisButton()
        browser.pause(1000)
        const topicsLabel = topicsPage.topicsLabel()
        console.log('"Topics" labe is displayed : ' + topicsLabel.isDisplayed())
    })

    it('check url contains function', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        const text = 'webdriverio'
        mainPage.setSearchInput(text)
        browser.pause(1000)
        mainPage.clickMagnifier()
        browser.pause(1000)
        searchWebdriverioPage.clickFirstResult()
        browser.pause(1000)
        const currentUrl = searchWebdriverioPage.currentUrl()
        const containing = currentUrl.includes("webdriverio")
        console.log('Current url has "webdriverio" : ' + containing)
    })

    it('enterprise pages testing', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        mainPage.clickEnterpriseButton()
        browser.pause(1000)
        enterprisePage.clickStartAFreeTrial()
        browser.pause(1000)
        enterprisePlanPage.clickEnterpriseCloudLabel()
        browser.pause(1000)
        var chance = new Chance()
        const userName = chance.string({ pool : 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' , length : chance.integer({ min : 5, max : 10 }) })
        const userEmail = chance.email()
        const pass = chance.string({length : 8})
        joinPage.setUserName(userName)
        browser.pause(500)
        joinPage.setUserEmail(userEmail)
        browser.pause(500)
        joinPage.setPass(pass)
        browser.pause(1000)
        browser.back()
        enterprisePlanPage.clickEnterpriseServerLabel()
        const name = chance.name()
        const company = chance.company()
        const phoneNumber = chance.phone()
        enterpriseTrialSignUpPage.setName(name)
        browser.pause(500)
        enterpriseTrialSignUpPage.setCompany(company)
        browser.pause(500)
        enterpriseTrialSignUpPage.setEmail(userEmail)
        browser.pause(500)
        enterpriseTrialSignUpPage.setPhoneNumber(phoneNumber)
        browser.pause(500)
        enterpriseTrialSignUpPage.clickNotSureRadioButton()
        browser.pause(500)
        enterpriseTrialSignUpPage.clickYesRadioButton()
        browser.pause(1000)
        enterpriseTrialSignUpPage.setTextField('test')
        browser.pause(500)
        enterpriseTrialSignUpPage.clickTermsCheckbox()
        browser.pause(2000)
    })

    it('console log all labels', () => {
        browser.url('https://github.com/')
        browser.setWindowSize(1920, 1080)
        mainPage.clickCareersButton()
        browser.pause(1000)
        careersPage.clickOpenPositionsButton()
        browser.pause(500)
        console.log(careersPage.listOfPositions())
    })

})